FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG APP=backend
RUN npx nest build ${APP}

# ---

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

ARG APP=backend
ENV APP=${APP}

CMD node dist/apps/$APP/main
